require("arpan404.plugins-setup")
require("arpan404.core.options")
require("arpan404.core.keymaps")
require("arpan404.core.colorscheme")
require("arpan404.plugins.nvim-tree")
require("arpan404.plugins.telescope")
require("arpan404.plugins.lsp.mason")
require("arpan404.plugins.lsp.lspconfig")